name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day at midnight UTC
  workflow_dispatch:       # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: raikwar7
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          # Plugins
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_streak: yes
          plugin_languages: yes
